# DEEP LEARNING

## Tuần 2: numpy, pandas, matplotlib

# NUMPY

In [34]:
# Numpy là thư viện kiểu list
# vì:
# - Numpy nhanh
# - Numpy có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng numpy thì: pip install numpy
import numpy as np

In [35]:
# - tạo 1 list

python_list = [1,2,3]

# - chuyển danh sách trên thành numpy list
numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [36]:
# list in python can support multiple data types
my_list = [1, "chào",True, 2.0]

In [37]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [38]:
# Chuyển đổi kiểu dữ liệu
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [39]:
# accsesing và indexing

x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [40]:
# lấy số 4
x[3]

np.int64(4)

In [41]:
# lấy nhiều hơn 1 phần tử
# công thức [start:and:step]
# lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [42]:
# lấy từ 3 - 8 theo 3 cách
x[2:8]
x[2:]
x[-6:]

array([3, 4, 5, 6, 7, 8])

In [43]:
# lấy số 3 và số 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [44]:
x[[2,4]]

array([3, 5])

In [45]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
# lấy số 2
np_list[0,1]

np.int64(2)

In [49]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [52]:
# lấy 3 4 5 6
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [55]:
# Cách 2
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [56]:
# lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [62]:
# lấy 1 5 theo 2 cách
np_list[[0,2],0]
np_list[0::2,0]

array([1, 5])

In [64]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [69]:
# lấy 2 6 10 14
np_list[:,1]


array([ 2,  6, 10, 14])

In [70]:
#lấy 7 11
np_list[[1,2],2]

array([ 7, 11])

In [75]:
# lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [76]:
# lấy 16 15 14 13
np_list[3, ::-1]

array([16, 15, 14, 13])

In [77]:
# C3
np_list[-1, ::-1]

array([16, 15, 14, 13])

In [1]:
# BTVN 1
# cho ma trận = [[99,99,99],
#                [99,99,99],
#                [99,99,99]]

# hãy tưởng tượng ô 99 trống 
# giả sử 1 là x
# giả sử 0 là o
# lấy đầu vào từ phía X và phía O luân phiên
# Nếu đầu vào từ phía X là (0,0)

# ma trận sẽ trở thành
# [[x,99,99],
#  [99,99,99],
#  [99,99,99]]

# nếu đầu vào từ phía O là (0,0)
# Thông báo họ nhập lại
# nếu k thì điền vào ma trận

# Thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi

import numpy as np
board = np.full((3,3), 99)
players = [1, 0] # 1 = X, 0 = O
turn = 0
def check(b, p):
    # kiểm tra hàng và cột
    for i in range(3):
        if np.all(b[i, :] == p) or np.all(b[:, i] == p):
            return True
    # kiểm tra chéo
    if np.all(np.diag(b) == p) or np.all(np.diag(np.fliplr(b)) == p):
        return True
    return False

while True:
    print("\nMa trận hiện tại:")
    print(board)

    player = players[turn % 2]
    symbol = "X" if player == 1 else "O"

    try:
        r = int(input(f"Người chơi {symbol} nhập dòng (0-2): "))
        c = int(input(f"Người chơi {symbol} nhập cột (0-2): "))
    except:
        print("Nhập số hợp lệ!")
        continue

    # kiểm tra ô trống
    if board[r, c] != 99:
        print("Ô này đã được đánh, nhập lại!")
        continue

    board[r, c] = player

    # kiểm tra thắng
    if check(board, player):
        print(board)
        print(f"Người chơi {symbol} thắng!")
        break

    turn += 1


Ma trận hiện tại:
[[99 99 99]
 [99 99 99]
 [99 99 99]]

Ma trận hiện tại:
[[ 1 99 99]
 [99 99 99]
 [99 99 99]]
Ô này đã được đánh, nhập lại!

Ma trận hiện tại:
[[ 1 99 99]
 [99 99 99]
 [99 99 99]]
Ô này đã được đánh, nhập lại!

Ma trận hiện tại:
[[ 1 99 99]
 [99 99 99]
 [99 99 99]]

Ma trận hiện tại:
[[ 1 99 99]
 [ 0 99 99]
 [99 99 99]]

Ma trận hiện tại:
[[ 1 99 99]
 [ 0 99  1]
 [99 99 99]]

Ma trận hiện tại:
[[ 1 99 99]
 [ 0 99  1]
 [99  0 99]]
Ô này đã được đánh, nhập lại!

Ma trận hiện tại:
[[ 1 99 99]
 [ 0 99  1]
 [99  0 99]]

Ma trận hiện tại:
[[ 1 99  1]
 [ 0 99  1]
 [99  0 99]]

Ma trận hiện tại:
[[ 1 99  1]
 [ 0 99  1]
 [ 0  0 99]]
[[ 1  1  1]
 [ 0 99  1]
 [ 0  0 99]]
Người chơi X thắng!


##### BTVN 1
###### Công nghệ sử dụng
- **NumPy**: dùng để tạo và xử lý ma trận 2 chiều
- Các hàm NumPy như `full()`, `all()`, `diag()` giúp kiểm tra dữ liệu
###### Cách hoạt động
- Khởi tạo ma trận 3×3 với giá trị là **99**
- Hai người chơi X (1) và O (0) nhập vị trí `(row, col)` luân phiên
- Nếu ô đã được đánh thì yêu cầu nhập lại
- Sau mỗi lượt, chương trình kiểm tra:
  - 3 phần tử liên tiếp theo hàng
  - 3 phần tử liên tiếp theo cột
  - 2 đường chéo
- Khi một người có đủ 3 phần tử liên tiếp, trò chơi kết thúc
###### Kết quả
- Ma trận được cập nhật sau mỗi lượt chơi
- Xác định chính xác người chiến thắng theo luật X/O

In [8]:
# BTVN 2

y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr = np.array(y)
# lấy 4,5,6
print(arr[1, :]) # lấy cả hàng thứ 1

# lấy 2,5
print(arr[0:2, 1]) # lấy cột thứ 1 của hàng 0 và 1

# lấy 3,4
print(arr[0, 2], arr[1, 0]) # lấy hàng 0 cột 2 và hàng 1 cột 0

# lấy 9,6,3
print(arr[::-1, 2]) # lấy cột 2 từ dưới lên trên

[4 5 6]
[2 5]
3 4
[9 6 3]


In [9]:
# BTVN 3

# cho x = [1,2,3,4,5,6,7,8,9,10]

# 1. Xuất ra các số chẵn sử dụng if
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension

x = [1,2,3,4,5,6,7,8,9,10]
for i in x: # duyệt từng phần tử trong x và kiểm tra điều kiện chia hết cho 2 để xác định số chẵn
    if i % 2 == 0:
        print(i)
even_numbers = [i for i in x if i % 2 == 0] # sử dụng list comprehension để tạo danh sách các số chẵn
print(even_numbers)

2
4
6
8
10
[2, 4, 6, 8, 10]


In [82]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [84]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [85]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
idx = [True, True, True, False, True, True, True, False, True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [88]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# BTVN 4
# tạo 1 mảng numpy có kích thước 150x5. giả sử mảng này chứa 150 mẫu dữ liệu
# của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương, điểm trung bình
# Tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là X 
# và cột cuối cùng thành Y

# Tách mảng X thành X_train và X_test trong đó X_train chứa 70% dữ liệu và tách
# Y thành Y_train và Y_test trong đó Y_train chứa 70% dữ liệu

# Tạo 10 tập dữ liệu X_train k chồng chéo nhau

import numpy as np
np.random.seed(42)
data = np.random.rand(150, 5)
# tách X và Y
X = data[:, :4]
Y = data[:, 4]
# chia train và test
train = int(0.7 * len(X))
X_train = X[:train]
X_test = X[train:]
Y_train = Y[:train]
Y_test = Y[train:]
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
# tạo 10 tập dữ liệu k chồng chéo nhau
X_train_sets = np.array_split(X_train, 10)
for i, part in enumerate(X_train_sets):
    print(f"Tập {i+1}: {part.shape}")

(105, 4)
(45, 4)
(105,)
(45,)
Tập 1: (11, 4)
Tập 2: (11, 4)
Tập 3: (11, 4)
Tập 4: (11, 4)
Tập 5: (11, 4)
Tập 6: (10, 4)
Tập 7: (10, 4)
Tập 8: (10, 4)
Tập 9: (10, 4)
Tập 10: (10, 4)


##### Công nghệ sử dụng
- **NumPy**: dùng để tạo và xử lý dữ liệu ngẫu nhiên
- Hàm `np.random.seed()` để kiểm soát quá trình sinh số ngẫu nhiên

##### Cách hoạt động
- NumPy tạo dữ liệu ngẫu nhiên dựa trên một giá trị khởi tạo (seed)
- Khi đặt `np.random.seed(42)`, mỗi lần chạy chương trình sẽ sinh ra **cùng một tập dữ liệu**
- Giúp kết quả không thay đổi giữa các lần chạy
